# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: essence.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import data_pb2 as data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='essence.proto',
  package='NydusNetwork.API.Protocol',
  syntax='proto3',
  serialized_pb=_b('\n\ressence.proto\x12\x19NydusNetwork.API.Protocol\x1a\ndata.proto\"\xf3\x04\n\x07\x45ssence\x12\x13\n\x0b\x44\x61taVersion\x18\x01 \x01(\t\x12\x11\n\tDataBuild\x18\x02 \x01(\x05\x12\x39\n\tabilities\x18\x03 \x03(\x0b\x32&.NydusNetwork.API.Protocol.AbilityData\x12\x32\n\x05\x62uffs\x18\x04 \x03(\x0b\x32#.NydusNetwork.API.Protocol.BuffData\x12:\n\tunitTypes\x18\x05 \x03(\x0b\x32\'.NydusNetwork.API.Protocol.UnitTypeData\x12\x38\n\x08upgrades\x18\x06 \x03(\x0b\x32&.NydusNetwork.API.Protocol.UpgradeData\x12@\n\runitProducers\x18\x07 \x03(\x0b\x32).NydusNetwork.API.Protocol.MultiValuePair\x12H\n\x15unitRequiredBuildings\x18\x08 \x03(\x0b\x32).NydusNetwork.API.Protocol.MultiValuePair\x12>\n\x10researchProducer\x18\t \x03(\x0b\x32$.NydusNetwork.API.Protocol.ValuePair\x12G\n\x19researchRequiredBuildings\x18\n \x03(\x0b\x32$.NydusNetwork.API.Protocol.ValuePair\x12\x46\n\x18researchRequiredResearch\x18\x0b \x03(\x0b\x32$.NydusNetwork.API.Protocol.ValuePair\"\'\n\tValuePair\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r\"-\n\x0eMultiValuePair\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x0e\n\x06values\x18\x02 \x03(\rb\x06proto3')
  ,
  dependencies=[data__pb2.DESCRIPTOR,])




_ESSENCE = _descriptor.Descriptor(
  name='Essence',
  full_name='NydusNetwork.API.Protocol.Essence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='DataVersion', full_name='NydusNetwork.API.Protocol.Essence.DataVersion', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DataBuild', full_name='NydusNetwork.API.Protocol.Essence.DataBuild', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='abilities', full_name='NydusNetwork.API.Protocol.Essence.abilities', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buffs', full_name='NydusNetwork.API.Protocol.Essence.buffs', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unitTypes', full_name='NydusNetwork.API.Protocol.Essence.unitTypes', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='upgrades', full_name='NydusNetwork.API.Protocol.Essence.upgrades', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unitProducers', full_name='NydusNetwork.API.Protocol.Essence.unitProducers', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unitRequiredBuildings', full_name='NydusNetwork.API.Protocol.Essence.unitRequiredBuildings', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='researchProducer', full_name='NydusNetwork.API.Protocol.Essence.researchProducer', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='researchRequiredBuildings', full_name='NydusNetwork.API.Protocol.Essence.researchRequiredBuildings', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='researchRequiredResearch', full_name='NydusNetwork.API.Protocol.Essence.researchRequiredResearch', index=10,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=684,
)


_VALUEPAIR = _descriptor.Descriptor(
  name='ValuePair',
  full_name='NydusNetwork.API.Protocol.ValuePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='NydusNetwork.API.Protocol.ValuePair.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='NydusNetwork.API.Protocol.ValuePair.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=686,
  serialized_end=725,
)


_MULTIVALUEPAIR = _descriptor.Descriptor(
  name='MultiValuePair',
  full_name='NydusNetwork.API.Protocol.MultiValuePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='NydusNetwork.API.Protocol.MultiValuePair.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='NydusNetwork.API.Protocol.MultiValuePair.values', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=727,
  serialized_end=772,
)

_ESSENCE.fields_by_name['abilities'].message_type = data__pb2._ABILITYDATA
_ESSENCE.fields_by_name['buffs'].message_type = data__pb2._BUFFDATA
_ESSENCE.fields_by_name['unitTypes'].message_type = data__pb2._UNITTYPEDATA
_ESSENCE.fields_by_name['upgrades'].message_type = data__pb2._UPGRADEDATA
_ESSENCE.fields_by_name['unitProducers'].message_type = _MULTIVALUEPAIR
_ESSENCE.fields_by_name['unitRequiredBuildings'].message_type = _MULTIVALUEPAIR
_ESSENCE.fields_by_name['researchProducer'].message_type = _VALUEPAIR
_ESSENCE.fields_by_name['researchRequiredBuildings'].message_type = _VALUEPAIR
_ESSENCE.fields_by_name['researchRequiredResearch'].message_type = _VALUEPAIR
DESCRIPTOR.message_types_by_name['Essence'] = _ESSENCE
DESCRIPTOR.message_types_by_name['ValuePair'] = _VALUEPAIR
DESCRIPTOR.message_types_by_name['MultiValuePair'] = _MULTIVALUEPAIR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Essence = _reflection.GeneratedProtocolMessageType('Essence', (_message.Message,), dict(
  DESCRIPTOR = _ESSENCE,
  __module__ = 'essence_pb2'
  # @@protoc_insertion_point(class_scope:NydusNetwork.API.Protocol.Essence)
  ))
_sym_db.RegisterMessage(Essence)

ValuePair = _reflection.GeneratedProtocolMessageType('ValuePair', (_message.Message,), dict(
  DESCRIPTOR = _VALUEPAIR,
  __module__ = 'essence_pb2'
  # @@protoc_insertion_point(class_scope:NydusNetwork.API.Protocol.ValuePair)
  ))
_sym_db.RegisterMessage(ValuePair)

MultiValuePair = _reflection.GeneratedProtocolMessageType('MultiValuePair', (_message.Message,), dict(
  DESCRIPTOR = _MULTIVALUEPAIR,
  __module__ = 'essence_pb2'
  # @@protoc_insertion_point(class_scope:NydusNetwork.API.Protocol.MultiValuePair)
  ))
_sym_db.RegisterMessage(MultiValuePair)


# @@protoc_insertion_point(module_scope)
