# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: query.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import error_pb2 as error__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='query.proto',
  package='NydusNetwork.API.Protocol',
  syntax='proto3',
  serialized_pb=_b('\n\x0bquery.proto\x12\x19NydusNetwork.API.Protocol\x1a\x0c\x63ommon.proto\x1a\x0b\x65rror.proto\"\x91\x02\n\x0cRequestQuery\x12?\n\x07pathing\x18\x01 \x03(\x0b\x32..NydusNetwork.API.Protocol.RequestQueryPathing\x12L\n\tabilities\x18\x02 \x03(\x0b\x32\x39.NydusNetwork.API.Protocol.RequestQueryAvailableAbilities\x12L\n\nplacements\x18\x03 \x03(\x0b\x32\x38.NydusNetwork.API.Protocol.RequestQueryBuildingPlacement\x12$\n\x1cignore_resource_requirements\x18\x04 \x01(\x08\"\xef\x01\n\rResponseQuery\x12@\n\x07pathing\x18\x01 \x03(\x0b\x32/.NydusNetwork.API.Protocol.ResponseQueryPathing\x12M\n\tabilities\x18\x02 \x03(\x0b\x32:.NydusNetwork.API.Protocol.ResponseQueryAvailableAbilities\x12M\n\nplacements\x18\x03 \x03(\x0b\x32\x39.NydusNetwork.API.Protocol.ResponseQueryBuildingPlacement\"\xa0\x01\n\x13RequestQueryPathing\x12\x37\n\tstart_pos\x18\x01 \x01(\x0b\x32\".NydusNetwork.API.Protocol.Point2DH\x00\x12\x12\n\x08unit_tag\x18\x02 \x01(\x04H\x00\x12\x33\n\x07\x65nd_pos\x18\x03 \x01(\x0b\x32\".NydusNetwork.API.Protocol.Point2DB\x07\n\x05start\"(\n\x14ResponseQueryPathing\x12\x10\n\x08\x64istance\x18\x01 \x01(\x02\"2\n\x1eRequestQueryAvailableAbilities\x12\x10\n\x08unit_tag\x18\x01 \x01(\x04\"\x89\x01\n\x1fResponseQueryAvailableAbilities\x12>\n\tabilities\x18\x01 \x03(\x0b\x32+.NydusNetwork.API.Protocol.AvailableAbility\x12\x10\n\x08unit_tag\x18\x02 \x01(\x04\x12\x14\n\x0cunit_type_id\x18\x03 \x01(\r\"\x85\x01\n\x1dRequestQueryBuildingPlacement\x12\x12\n\nability_id\x18\x01 \x01(\x05\x12\x36\n\ntarget_pos\x18\x02 \x01(\x0b\x32\".NydusNetwork.API.Protocol.Point2D\x12\x18\n\x10placing_unit_tag\x18\x03 \x01(\x04\"Y\n\x1eResponseQueryBuildingPlacement\x12\x37\n\x06result\x18\x01 \x01(\x0e\x32\'.NydusNetwork.API.Protocol.ActionResultb\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,error__pb2.DESCRIPTOR,])




_REQUESTQUERY = _descriptor.Descriptor(
  name='RequestQuery',
  full_name='NydusNetwork.API.Protocol.RequestQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pathing', full_name='NydusNetwork.API.Protocol.RequestQuery.pathing', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='abilities', full_name='NydusNetwork.API.Protocol.RequestQuery.abilities', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='placements', full_name='NydusNetwork.API.Protocol.RequestQuery.placements', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ignore_resource_requirements', full_name='NydusNetwork.API.Protocol.RequestQuery.ignore_resource_requirements', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=343,
)


_RESPONSEQUERY = _descriptor.Descriptor(
  name='ResponseQuery',
  full_name='NydusNetwork.API.Protocol.ResponseQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pathing', full_name='NydusNetwork.API.Protocol.ResponseQuery.pathing', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='abilities', full_name='NydusNetwork.API.Protocol.ResponseQuery.abilities', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='placements', full_name='NydusNetwork.API.Protocol.ResponseQuery.placements', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=585,
)


_REQUESTQUERYPATHING = _descriptor.Descriptor(
  name='RequestQueryPathing',
  full_name='NydusNetwork.API.Protocol.RequestQueryPathing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_pos', full_name='NydusNetwork.API.Protocol.RequestQueryPathing.start_pos', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unit_tag', full_name='NydusNetwork.API.Protocol.RequestQueryPathing.unit_tag', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_pos', full_name='NydusNetwork.API.Protocol.RequestQueryPathing.end_pos', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='start', full_name='NydusNetwork.API.Protocol.RequestQueryPathing.start',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=588,
  serialized_end=748,
)


_RESPONSEQUERYPATHING = _descriptor.Descriptor(
  name='ResponseQueryPathing',
  full_name='NydusNetwork.API.Protocol.ResponseQueryPathing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='distance', full_name='NydusNetwork.API.Protocol.ResponseQueryPathing.distance', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=750,
  serialized_end=790,
)


_REQUESTQUERYAVAILABLEABILITIES = _descriptor.Descriptor(
  name='RequestQueryAvailableAbilities',
  full_name='NydusNetwork.API.Protocol.RequestQueryAvailableAbilities',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unit_tag', full_name='NydusNetwork.API.Protocol.RequestQueryAvailableAbilities.unit_tag', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=792,
  serialized_end=842,
)


_RESPONSEQUERYAVAILABLEABILITIES = _descriptor.Descriptor(
  name='ResponseQueryAvailableAbilities',
  full_name='NydusNetwork.API.Protocol.ResponseQueryAvailableAbilities',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='abilities', full_name='NydusNetwork.API.Protocol.ResponseQueryAvailableAbilities.abilities', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unit_tag', full_name='NydusNetwork.API.Protocol.ResponseQueryAvailableAbilities.unit_tag', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unit_type_id', full_name='NydusNetwork.API.Protocol.ResponseQueryAvailableAbilities.unit_type_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=845,
  serialized_end=982,
)


_REQUESTQUERYBUILDINGPLACEMENT = _descriptor.Descriptor(
  name='RequestQueryBuildingPlacement',
  full_name='NydusNetwork.API.Protocol.RequestQueryBuildingPlacement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ability_id', full_name='NydusNetwork.API.Protocol.RequestQueryBuildingPlacement.ability_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_pos', full_name='NydusNetwork.API.Protocol.RequestQueryBuildingPlacement.target_pos', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='placing_unit_tag', full_name='NydusNetwork.API.Protocol.RequestQueryBuildingPlacement.placing_unit_tag', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=985,
  serialized_end=1118,
)


_RESPONSEQUERYBUILDINGPLACEMENT = _descriptor.Descriptor(
  name='ResponseQueryBuildingPlacement',
  full_name='NydusNetwork.API.Protocol.ResponseQueryBuildingPlacement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='NydusNetwork.API.Protocol.ResponseQueryBuildingPlacement.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1120,
  serialized_end=1209,
)

_REQUESTQUERY.fields_by_name['pathing'].message_type = _REQUESTQUERYPATHING
_REQUESTQUERY.fields_by_name['abilities'].message_type = _REQUESTQUERYAVAILABLEABILITIES
_REQUESTQUERY.fields_by_name['placements'].message_type = _REQUESTQUERYBUILDINGPLACEMENT
_RESPONSEQUERY.fields_by_name['pathing'].message_type = _RESPONSEQUERYPATHING
_RESPONSEQUERY.fields_by_name['abilities'].message_type = _RESPONSEQUERYAVAILABLEABILITIES
_RESPONSEQUERY.fields_by_name['placements'].message_type = _RESPONSEQUERYBUILDINGPLACEMENT
_REQUESTQUERYPATHING.fields_by_name['start_pos'].message_type = common__pb2._POINT2D
_REQUESTQUERYPATHING.fields_by_name['end_pos'].message_type = common__pb2._POINT2D
_REQUESTQUERYPATHING.oneofs_by_name['start'].fields.append(
  _REQUESTQUERYPATHING.fields_by_name['start_pos'])
_REQUESTQUERYPATHING.fields_by_name['start_pos'].containing_oneof = _REQUESTQUERYPATHING.oneofs_by_name['start']
_REQUESTQUERYPATHING.oneofs_by_name['start'].fields.append(
  _REQUESTQUERYPATHING.fields_by_name['unit_tag'])
_REQUESTQUERYPATHING.fields_by_name['unit_tag'].containing_oneof = _REQUESTQUERYPATHING.oneofs_by_name['start']
_RESPONSEQUERYAVAILABLEABILITIES.fields_by_name['abilities'].message_type = common__pb2._AVAILABLEABILITY
_REQUESTQUERYBUILDINGPLACEMENT.fields_by_name['target_pos'].message_type = common__pb2._POINT2D
_RESPONSEQUERYBUILDINGPLACEMENT.fields_by_name['result'].enum_type = error__pb2._ACTIONRESULT
DESCRIPTOR.message_types_by_name['RequestQuery'] = _REQUESTQUERY
DESCRIPTOR.message_types_by_name['ResponseQuery'] = _RESPONSEQUERY
DESCRIPTOR.message_types_by_name['RequestQueryPathing'] = _REQUESTQUERYPATHING
DESCRIPTOR.message_types_by_name['ResponseQueryPathing'] = _RESPONSEQUERYPATHING
DESCRIPTOR.message_types_by_name['RequestQueryAvailableAbilities'] = _REQUESTQUERYAVAILABLEABILITIES
DESCRIPTOR.message_types_by_name['ResponseQueryAvailableAbilities'] = _RESPONSEQUERYAVAILABLEABILITIES
DESCRIPTOR.message_types_by_name['RequestQueryBuildingPlacement'] = _REQUESTQUERYBUILDINGPLACEMENT
DESCRIPTOR.message_types_by_name['ResponseQueryBuildingPlacement'] = _RESPONSEQUERYBUILDINGPLACEMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestQuery = _reflection.GeneratedProtocolMessageType('RequestQuery', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTQUERY,
  __module__ = 'query_pb2'
  # @@protoc_insertion_point(class_scope:NydusNetwork.API.Protocol.RequestQuery)
  ))
_sym_db.RegisterMessage(RequestQuery)

ResponseQuery = _reflection.GeneratedProtocolMessageType('ResponseQuery', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEQUERY,
  __module__ = 'query_pb2'
  # @@protoc_insertion_point(class_scope:NydusNetwork.API.Protocol.ResponseQuery)
  ))
_sym_db.RegisterMessage(ResponseQuery)

RequestQueryPathing = _reflection.GeneratedProtocolMessageType('RequestQueryPathing', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTQUERYPATHING,
  __module__ = 'query_pb2'
  # @@protoc_insertion_point(class_scope:NydusNetwork.API.Protocol.RequestQueryPathing)
  ))
_sym_db.RegisterMessage(RequestQueryPathing)

ResponseQueryPathing = _reflection.GeneratedProtocolMessageType('ResponseQueryPathing', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEQUERYPATHING,
  __module__ = 'query_pb2'
  # @@protoc_insertion_point(class_scope:NydusNetwork.API.Protocol.ResponseQueryPathing)
  ))
_sym_db.RegisterMessage(ResponseQueryPathing)

RequestQueryAvailableAbilities = _reflection.GeneratedProtocolMessageType('RequestQueryAvailableAbilities', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTQUERYAVAILABLEABILITIES,
  __module__ = 'query_pb2'
  # @@protoc_insertion_point(class_scope:NydusNetwork.API.Protocol.RequestQueryAvailableAbilities)
  ))
_sym_db.RegisterMessage(RequestQueryAvailableAbilities)

ResponseQueryAvailableAbilities = _reflection.GeneratedProtocolMessageType('ResponseQueryAvailableAbilities', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEQUERYAVAILABLEABILITIES,
  __module__ = 'query_pb2'
  # @@protoc_insertion_point(class_scope:NydusNetwork.API.Protocol.ResponseQueryAvailableAbilities)
  ))
_sym_db.RegisterMessage(ResponseQueryAvailableAbilities)

RequestQueryBuildingPlacement = _reflection.GeneratedProtocolMessageType('RequestQueryBuildingPlacement', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTQUERYBUILDINGPLACEMENT,
  __module__ = 'query_pb2'
  # @@protoc_insertion_point(class_scope:NydusNetwork.API.Protocol.RequestQueryBuildingPlacement)
  ))
_sym_db.RegisterMessage(RequestQueryBuildingPlacement)

ResponseQueryBuildingPlacement = _reflection.GeneratedProtocolMessageType('ResponseQueryBuildingPlacement', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSEQUERYBUILDINGPLACEMENT,
  __module__ = 'query_pb2'
  # @@protoc_insertion_point(class_scope:NydusNetwork.API.Protocol.ResponseQueryBuildingPlacement)
  ))
_sym_db.RegisterMessage(ResponseQueryBuildingPlacement)


# @@protoc_insertion_point(module_scope)
